/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALCULADORA 0x31111111
#define OPERACIONES 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(int *, CLIENT *);
extern  int * suma_1_svc(int *, struct svc_req *);
#define RESTA 2
extern  int * resta_1(int *, CLIENT *);
extern  int * resta_1_svc(int *, struct svc_req *);
#define MULTIPLICACION 3
extern  int * multiplicacion_1(int *, CLIENT *);
extern  int * multiplicacion_1_svc(int *, struct svc_req *);
#define DIVICION 4
extern  float * divicion_1(int *, CLIENT *);
extern  float * divicion_1_svc(int *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define MULTIPLICACION 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define DIVICION 4
extern  float * divicion_1();
extern  float * divicion_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
